CREATE SCHEMA ESHOP_DESIGN_PATTERNS;

DROP TABLE IF EXISTS ESHOP_DESIGN_PATTERNS.TBUSER;
DROP TABLE IF EXISTS ESHOP_DESIGN_PATTERNS.TBUSERPROFILE;
DROP TABLE IF EXISTS ESHOP_DESIGN_PATTERNS.TBADDRESS;
DROP TABLE IF EXISTS ESHOP_DESIGN_PATTERNS.TBCATEGORY;
DROP TABLE IF EXISTS ESHOP_DESIGN_PATTERNS.TBCHARACTERISTIC;
DROP TABLE IF EXISTS ESHOP_DESIGN_PATTERNS.TBPRODUCT;

CREATE TABLE IF NOT EXISTS ESHOP_DESIGN_PATTERNS.TBUSER (
    USER_ID BIGINT NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    DISCRIMINATOR VARCHAR(1)
);

CREATE TABLE IF NOT EXISTS ESHOP_DESIGN_PATTERNS.TBUSERPROFILE(
    USER_ID BIGINT NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    PHONE_NO VARCHAR(20) NOT NULL,
    DATE_ADDED DATE NOT NULL,
    DATE_LAST_MODIFIED DATE,
    DISCRIMINATOR VARCHAR(1)
);

CREATE TABLE IF NOT EXISTS ESHOP_DESIGN_PATTERNS.TBADDRESS(
    ADDRESS_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    STREET_NAME VARCHAR(50) NOT NULL,
    STREET_NUMBER VARCHAR(50) NOT NULL,
    POSTAL_CODE VARCHAR(50) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL,
    DISCRIMINATOR VARCHAR(1)
);

CREATE TABLE IF NOT EXISTS ESHOP_DESIGN_PATTERNS.TBCATEGORY(
    CATEGORY_ID BIGINT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(250),
    DISCRIMINATOR VARCHAR(1)
);

CREATE TABLE IF NOT EXISTS ESHOP_DESIGN_PATTERNS.TBCHARACTERISTIC(
    CHARACTERISTIC_ID BIGINT NOT NULL,
    CATEGORY_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    VALUE VARCHAR(100) NOT NULL,
    DISCRIMINATOR VARCHAR(1)
);

CREATE TABLE IF NOT EXISTS ESHOP_DESIGN_PATTERNS.TBPRODUCT(
    PRODUCT_ID BIGINT NOT NULL,
    CATEGORY_ID BIGINT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    SKU VARCHAR(100) NOT NULL,
    INVENTORY_COUNT INTEGER NOT NULL,
    INVENTORY_LIMIT INTEGER NOT NULL,
    PRICE DECIMAL(8,2) NOT NULL,
    DESCRIPTION VARCHAR(250),
    DATE_ADDED DATE NOT NULL,
    DATE_LAST_MODIFIED DATE,
    DISCRIMINATOR VARCHAR(1)
);

-- PKs
ALTER TABLE ESHOP_DESIGN_PATTERNS.TBUSER ADD CONSTRAINT PKTBUSER PRIMARY KEY(USER_ID);
ALTER TABLE ESHOP_DESIGN_PATTERNS.TBUSERPROFILE ADD CONSTRAINT PKTBUSERPROFILE PRIMARY KEY(USER_ID);
ALTER TABLE ESHOP_DESIGN_PATTERNS.TBADDRESS ADD CONSTRAINT PKTBADDRESS PRIMARY KEY(ADDRESS_ID, USER_ID);
ALTER TABLE ESHOP_DESIGN_PATTERNS.TBCATEGORY ADD CONSTRAINT PKTBCATEGORY PRIMARY KEY(CATEGORY_ID);
ALTER TABLE ESHOP_DESIGN_PATTERNS.TBCHARACTERISTIC ADD CONSTRAINT PKTBCHARACTERISTIC PRIMARY KEY(CHARACTERISTIC_ID, CATEGORY_ID, PRODUCT_ID);
ALTER TABLE ESHOP_DESIGN_PATTERNS.TBPRODUCT ADD CONSTRAINT PKTBPRODUCT PRIMARY KEY(PRODUCT_ID, CATEGORY_ID);

-- FKs
ALTER TABLE ESHOP_DESIGN_PATTERNS.TBUSERPROFILE ADD CONSTRAINT FKUSERPROFILEUSER FOREIGN KEY(USER_ID) REFERENCES ESHOP_DESIGN_PATTERNS.TBUSER(USER_ID) ON DELETE CASCADE;
ALTER TABLE ESHOP_DESIGN_PATTERNS.TBADDRESS ADD CONSTRAINT FKADDRESSUSERPROFILE FOREIGN KEY(USER_ID) REFERENCES ESHOP_DESIGN_PATTERNS.TBUSERPROFILE(USER_ID) ON DELETE CASCADE;
ALTER TABLE ESHOP_DESIGN_PATTERNS.TBCHARACTERISTIC ADD CONSTRAINT FKCHARACTERISTICPRODUCT FOREIGN KEY(PRODUCT_ID, CATEGORY_ID) REFERENCES ESHOP_DESIGN_PATTERNS.TBPRODUCT(PRODUCT_ID, CATEGORY_ID) ON DELETE CASCADE;
ALTER TABLE ESHOP_DESIGN_PATTERNS.TBPRODUCT ADD CONSTRAINT FKPRODUCTCATEGORY FOREIGN KEY(CATEGORY_ID) REFERENCES ESHOP_DESIGN_PATTERNS.TBCATEGORY(CATEGORY_ID) ON DELETE CASCADE;

-- Sequences
CREATE SEQUENCE USER_ID_SEQUENCE START 100;
CREATE SEQUENCE ADDRESS_ID_SEQUENCE START 100;
CREATE SEQUENCE CATEGORY_ID_SEQUENCE START 100;
CREATE SEQUENCE PRODUCT_ID_SEQUENCE START 100;
CREATE SEQUENCE CHARACTERISTIC_ID_SEQUENCE START 100;

--TODO: Make category name unique
--TODO: Cleanup Pom.xml files. Move dependencies to parent.
