CREATE SCHEMA ESHOP_DESIGN_PATTERNS

CREATE TABLE IF NOT EXISTS ESHOP_DESIGN_PATTERNS.TBUSER (
    USER_ID BIGINT NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL
);

--    DISCRIMINATOR VARCHAR(1)

CREATE TABLE IF NOT EXISTS ESHOP_DESIGN_PATTERNS.TBUSERPROFILE(
    USER_ID BIGINT NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    PHONE_NO VARCHAR(20) NOT NULL,
    DATE_ADDED DATE NOT NULL,
    DATE_LAST_MODIFIED DATE
);

-- PKs
ALTER TABLE ESHOP_DESIGN_PATTERNS.TBUSER ADD CONSTRAINT PKTBUSER PRIMARY KEY(USER_ID);
ALTER TABLE ESHOP_DESIGN_PATTERNS.TBUSERPROFILE ADD CONSTRAINT PKTBUSERPROFILE PRIMARY KEY(USER_ID);

-- FKs
ALTER TABLE ESHOP_DESIGN_PATTERNS.TBUSERPROFILE ADD CONSTRAINT FKUSERPROFILEUSER FOREIGN KEY(USER_ID) REFERENCES ESHOP_DESIGN_PATTERNS.TBUSER(USER_ID) ON DELETE CASCADE;